### ISSUE TITLE
Overwrites {{ build }} jinja

### ISSUE THREAD

**Issue by tkelman** [regro/cf-graph#26]
see https://github.com/conda-forge/awscli-feedstock/pull/29

**Comment by CJ-Wright** [comment]
Thank you for reporting!

**Comment by CJ-Wright** [comment]
This came about because you were able to update the version before the bot realized there is a new version. Normally that PR would have included a version bump.

@scopatz thoughts?
This is being overwritten because in the replacements a) there is no `{{ build ...}` in our replacement setup, b) there is also a replacement which overwrites the build setting. I don't suppose that there is a meaningful way to do this in the regex?

To be fair, having the build number as a jinja variable is a bit uncommon, especially as it is usually only used once, hence why we didn't include it in the initial setup.

**Comment by scopatz** [comment]
Well, you could check and make sure that the `build: NUM` really is just a a simple number before overwriting it.  If it isn't you can punt.

**Comment by scopatz** [comment]
Basically, this comes down to the fact that the ticker is assuming that there is a specific form of meta.yaml, and if it isn't in that form, it will fail

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #32](https://github.com/regro/cf-scripts/issues/32) via [**ZenHub**](https://www.zenhub.com/)
